import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import sharp from "sharp";

const here = dirname(fileURLToPath(import.meta.url));
const websiteDir = join(here, "..");
const repoRoot = join(websiteDir, "..", "..");
const assetsDir = join(repoRoot, "assets");
const publicDir = join(websiteDir, "public");
const imagesDir = join(publicDir, "images");
const typesFile = join(websiteDir, "src", "lib", "images.ts");

/** WebP sizes emitted for on-page logo use. */
const WEBP_SIZES = [32, 64, 96, 128, 180, 200, 300, 400] as const;
/** Single PNG favicon size (browsers scale as needed). */
const FAVICON_SIZE = 64;

/** Transparent background for `fit: contain` letterboxing of the square logos. */
const TRANSPARENT = { r: 0, g: 0, b: 0, alpha: 0 } as const;

interface Variant {
  /** Output base name and source file stem. */
  name: string;
  /** Source PNG in the repo-root assets folder. */
  source: string;
  /** Favicon file name written to public/. */
  favicon: string;
}

// The light-variant art is drawn for light backgrounds -> light-mode favicon;
// the dark-variant -> dark-mode favicon.
const VARIANTS: readonly Variant[] = [
  {
    name: "webbuf-2-light",
    source: "webbuf-2-light.png",
    favicon: "favicon-light.png",
  },
  {
    name: "webbuf-2-dark",
    source: "webbuf-2-dark.png",
    favicon: "favicon-dark.png",
  },
];

async function main(): Promise<void> {
  await mkdir(imagesDir, { recursive: true });

  const webPaths: string[] = [];

  for (const variant of VARIANTS) {
    const src = join(assetsDir, variant.source);

    for (const size of WEBP_SIZES) {
      const fileName = `${variant.name}-${size}.webp`;
      await sharp(src)
        .resize(size, size, { fit: "contain", background: TRANSPARENT })
        .webp({ quality: 92 })
        .toFile(join(imagesDir, fileName));
      webPaths.push(`/images/${fileName}`);
      console.log(`webp  ${fileName}`);
    }

    await sharp(src)
      .resize(FAVICON_SIZE, FAVICON_SIZE, {
        fit: "contain",
        background: TRANSPARENT,
      })
      .png()
      .toFile(join(publicDir, variant.favicon));
    console.log(`png   ${variant.favicon}`);
  }

  const sorted = [...webPaths].sort();
  const contents = `// Generated by scripts/process-images.ts -- do not edit by hand.
export type SiteImage =
${sorted.map((path) => `  | "${path}"`).join("\n")};

export const siteImage = (image: SiteImage): SiteImage => image;
`;
  await writeFile(typesFile, contents);
  console.log(`types ${typesFile}`);
}

await main();
