// Generated by scripts/process-images.ts -- do not edit by hand.
export type SiteImage =
  | "/images/webbuf-2-dark-128.webp"
  | "/images/webbuf-2-dark-180.webp"
  | "/images/webbuf-2-dark-200.webp"
  | "/images/webbuf-2-dark-300.webp"
  | "/images/webbuf-2-dark-32.webp"
  | "/images/webbuf-2-dark-400.webp"
  | "/images/webbuf-2-dark-64.webp"
  | "/images/webbuf-2-dark-96.webp"
  | "/images/webbuf-2-light-128.webp"
  | "/images/webbuf-2-light-180.webp"
  | "/images/webbuf-2-light-200.webp"
  | "/images/webbuf-2-light-300.webp"
  | "/images/webbuf-2-light-32.webp"
  | "/images/webbuf-2-light-400.webp"
  | "/images/webbuf-2-light-64.webp"
  | "/images/webbuf-2-light-96.webp";

export const siteImage = (image: SiteImage): SiteImage => image;
